import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const en = { common: { home: 'Home', services: 'Services', about: 'About us', contact: 'Contact', signUp: 'Sign up', backHome: 'Back to home', language: 'Language', account: 'My account', logout: 'Log out' }, hero: { title: 'No LIMITS.\nENDLESS\nOpportunities!', text: 'A platform that empowers women to discover careers, connect with employers, and grow their businesses—all in one place.', explore: 'Explore Services', learn: 'Learn More' }, services: { eyebrow: 'What we offer', title: 'Three Ways To Move Forward', text: 'Whether you’re searching, hiring, or building — Wiryaa meets you exactly where you are.', find: 'Find Jobs', hire: 'Hire Talents', career: 'Career Discovery', smart: 'Smart Hiring', start: 'Start Your Journey', findText: 'Our AI engine reads your profile, skills, and aspirations to surface roles perfectly matched to you. Salary benchmarks, insider tips, and career clarity — all at your fingertips.', hireText: 'Stop sifting through hundreds of CVs. Wiryaa ranks women candidates by fit, culture-match, and skill depth—so you connect with the right person faster, with less bias.' }, footer: { description: 'Careers, hiring and entrepreneurship—built to help women move forward.', quick: 'Quick Links', marketplace: 'Marketplace', loop: 'Stay in the loop', updates: 'Get opportunities and thoughtful updates.', subscribe: 'Subscribe', subscribed: 'Subscribed!', rights: '© 2026 Wiryaa. All rights reserved.', privacy: 'Privacy', terms: 'Terms', built: 'India · Built with purpose' } }
const hi = { common: { home: 'होम', services: 'सेवाएँ', about: 'हमारे बारे में', contact: 'संपर्क', signUp: 'साइन अप', backHome: 'होम पर वापस', language: 'भाषा', account: 'मेरा अकाउंट', logout: 'लॉग आउट' }, hero: { title: 'कोई सीमा नहीं।\nअनंत\nअवसर!', text: 'एक मंच जो महिलाओं को करियर खोजने, नियोक्ताओं से जुड़ने और अपने व्यवसाय बढ़ाने में सक्षम बनाता है।', explore: 'सेवाएँ देखें', learn: 'और जानें' }, services: { eyebrow: 'हमारी सेवाएँ', title: 'आगे बढ़ने के तीन तरीके', text: 'चाहे आप खोज रही हों, नियुक्ति कर रही हों या निर्माण कर रही हों—Wiryaa आपके साथ है।', find: 'नौकरियाँ खोजें', hire: 'प्रतिभाओं को नियुक्त करें', career: 'करियर खोज', smart: 'स्मार्ट हायरिंग', start: 'अपनी यात्रा शुरू करें', findText: 'हमारा एआई आपके प्रोफ़ाइल, कौशल और आकांक्षाओं को समझकर आपके लिए सही भूमिकाएँ खोजता है। वेतन जानकारी, सुझाव और करियर स्पष्टता—सब एक ही जगह।', hireText: 'सैकड़ों CV छाँटना बंद करें। Wiryaa सही उम्मीदवारों से तेज़ी और कम पक्षपात के साथ जुड़ने में मदद करता है।' }, footer: { description: 'करियर, नियुक्ति और उद्यमिता—महिलाओं को आगे बढ़ाने के लिए।', quick: 'त्वरित लिंक', marketplace: 'मार्केटप्लेस', loop: 'जुड़े रहें', updates: 'अवसर और उपयोगी अपडेट पाएं।', subscribe: 'सब्सक्राइब करें', subscribed: 'सब्सक्राइब हो गया!', rights: '© 2026 Wiryaa. सर्वाधिकार सुरक्षित।', privacy: 'गोपनीयता', terms: 'नियम', built: 'भारत · उद्देश्य के साथ निर्मित' } }
const mr = { common: { home: 'मुख्यपृष्ठ', services: 'सेवा', about: 'आमच्याबद्दल', contact: 'संपर्क', signUp: 'साइन अप', backHome: 'मुख्यपृष्ठावर परत', language: 'भाषा', account: 'माझे खाते', logout: 'लॉग आउट' }, hero: { title: 'मर्यादा नाहीत.\nअमर्याद\nसंधी!', text: 'महिलांना करिअर शोधण्यासाठी, नियोक्त्यांशी जोडण्यासाठी आणि व्यवसाय वाढवण्यासाठी सक्षम करणारे व्यासपीठ.', explore: 'सेवा पहा', learn: 'अधिक जाणून घ्या' }, services: { eyebrow: 'आम्ही काय देतो', title: 'पुढे जाण्याचे तीन मार्ग', text: 'तुम्ही शोधत असाल, नियुक्ती करत असाल किंवा उभारत असाल—Wiryaa तुमच्यासोबत आहे.', find: 'नोकऱ्या शोधा', hire: 'प्रतिभांना नियुक्त करा', career: 'करिअर शोध', smart: 'स्मार्ट हायरिंग', start: 'तुमचा प्रवास सुरू करा', findText: 'आमचे एआय तुमचे प्रोफाइल, कौशल्ये आणि आकांक्षा समजून तुमच्यासाठी योग्य भूमिका शोधते. पगार माहिती, टिप्स आणि करिअरची स्पष्टता—सर्व एकाच ठिकाणी.', hireText: 'शेकडो CV तपासणे थांबवा. Wiryaa योग्य उमेदवारांशी जलद आणि कमी पक्षपाताने जोडण्यात मदत करते.' }, footer: { description: 'करिअर, नियुक्ती आणि उद्योजकता—महिलांना पुढे नेण्यासाठी.', quick: 'द्रुत दुवे', marketplace: 'बाजारपेठ', loop: 'संपर्कात रहा', updates: 'संधी आणि उपयुक्त अपडेट मिळवा.', subscribe: 'सदस्य व्हा', subscribed: 'सदस्यत्व घेतले!', rights: '© 2026 Wiryaa. सर्व हक्क राखीव.', privacy: 'गोपनीयता', terms: 'अटी', built: 'भारत · उद्देशाने निर्मित' } }
en.findJobs = {
  workspace: 'Career workspace', dashboard: 'Back to home', yourJourney: 'Your journey', create: 'Create Profile', profile: 'View Profile', recommendations: 'View Job Recommendations', tip: 'Your details are only used to personalise your career journey.', comingSoon: 'We are thoughtfully shaping this space for you. Check back soon.', createIntro: 'Tell us about your experience, strengths and what comes next.', personal: 'Personal information', personalHelp: 'The essentials that help employers get to know you.', name: 'Full name', namePlaceholder: 'e.g. Ananya Sharma', email: 'Email address', emailPlaceholder: 'you@example.com', phone: 'Phone number', phonePlaceholder: 'e.g. 98765 43210', age: 'Age', agePlaceholder: 'e.g. 27', state: 'State', statePlaceholder: 'e.g. Maharashtra', city: 'City', cityPlaceholder: 'e.g. Pune', pincode: 'Pincode', pincodePlaceholder: '6-digit pincode', profilePicture: 'Add profile photo', photoHelp: 'A clear, professional photo helps your profile feel more personal.', educationWork: 'Education & work experience', educationHelp: 'Share the work, learning and accomplishments you are proud of.', qualification: 'Highest qualification', qualificationPlaceholder: 'e.g. B.Com, Bachelor of Commerce', skills: 'Skills', skillsPlaceholder: 'List your technical, professional and people skills.', previousJobs: 'Previous jobs / internships', previousJobsPlaceholder: 'Where you worked, your title and dates.', roles: 'Roles & responsibilities', rolesPlaceholder: 'Describe the difference you made in each role.', skillsApplied: 'Skills applied', skillsAppliedPlaceholder: 'Which skills did you use in your work?', certifications: 'Certifications / achievements', certificationsPlaceholder: 'Awards, courses, licences or milestones.', resume: 'Resume / CV', resumeHint: 'Upload a PDF, DOC or DOCX', portfolio: 'Portfolio / resume link', portfolioPlaceholder: 'Portfolio, Google Drive or LinkedIn URL', workSamples: 'Work samples', workSamplesHint: 'Photos, videos or documents of your work', preferences: 'Preferences & constraints', preferencesHelp: 'Help us recommend opportunities that fit your life.', yourPreferences: 'Your preferences', preferencesPlaceholder: 'Tell us about roles, work style, location, salary expectations, schedule or other needs.', requiredNote: '* Required fields', saveProfile: 'Save my profile', saved: 'Your profile has been saved locally. You can continue refining it anytime.'
}
hi.findJobs = { ...en.findJobs, workspace: 'करियर वर्कस्पेस', dashboard: 'होम पर वापस', yourJourney: 'आपकी यात्रा', create: 'प्रोफ़ाइल बनाएँ', profile: 'प्रोफ़ाइल देखें', recommendations: 'नौकरी सुझाव देखें', tip: 'आपकी जानकारी का उपयोग केवल आपके करियर अनुभव को व्यक्तिगत बनाने के लिए किया जाता है।', comingSoon: 'हम आपके लिए इस जगह को ध्यान से तैयार कर रहे हैं। जल्द ही वापस आएँ।', createIntro: 'अपने अनुभव, ताकत और अगले कदम के बारे में बताएँ।', personal: 'व्यक्तिगत जानकारी', personalHelp: 'ज़रूरी जानकारी जिससे नियोक्ता आपको जान सकें।', name: 'पूरा नाम', email: 'ईमेल पता', phone: 'फ़ोन नंबर', age: 'आयु', state: 'राज्य', city: 'शहर', pincode: 'पिनकोड', profilePicture: 'फ़ोटो जोड़ें', educationWork: 'शिक्षा और कार्य अनुभव', educationHelp: 'अपने काम, सीख और उपलब्धियाँ साझा करें।', qualification: 'उच्चतम योग्यता', skills: 'कौशल', previousJobs: 'पिछली नौकरियाँ / इंटर्नशिप', roles: 'भूमिकाएँ और जिम्मेदारियाँ', skillsApplied: 'लागू किए गए कौशल', certifications: 'प्रमाणपत्र / उपलब्धियाँ', resume: 'रिज़्यूमे / CV', portfolio: 'पोर्टफोलियो / रिज़्यूमे लिंक', workSamples: 'कार्य नमूने', preferences: 'पसंद और सीमाएँ', preferencesHelp: 'ऐसे अवसर सुझाने में मदद करें जो आपके जीवन के अनुकूल हों।', yourPreferences: 'आपकी प्राथमिकताएँ', requiredNote: '* आवश्यक फ़ील्ड', saveProfile: 'मेरी प्रोफ़ाइल सहेजें', saved: 'आपकी प्रोफ़ाइल स्थानीय रूप से सहेज ली गई है।' }
mr.findJobs = { ...en.findJobs, workspace: 'करिअर कार्यक्षेत्र', dashboard: 'मुख्यपृष्ठावर परत', yourJourney: 'तुमचा प्रवास', create: 'प्रोफाइल तयार करा', profile: 'प्रोफाइल पहा', recommendations: 'नोकरी शिफारसी पहा', tip: 'तुमची माहिती केवळ तुमचा करिअर प्रवास वैयक्तिक करण्यासाठी वापरली जाते.', comingSoon: 'आम्ही तुमच्यासाठी ही जागा विचारपूर्वक तयार करत आहोत. लवकरच पुन्हा या.', createIntro: 'तुमचा अनुभव, सामर्थ्य आणि पुढील पाऊल सांगा.', personal: 'वैयक्तिक माहिती', personalHelp: 'नियोक्त्यांना तुम्हाला ओळखण्यासाठी आवश्यक माहिती.', name: 'पूर्ण नाव', email: 'ईमेल पत्ता', phone: 'फोन नंबर', age: 'वय', state: 'राज्य', city: 'शहर', pincode: 'पिनकोड', profilePicture: 'फोटो जोडा', educationWork: 'शिक्षण आणि कामाचा अनुभव', educationHelp: 'तुमचे काम, शिक्षण आणि अभिमानाच्या उपलब्धी सांगा.', qualification: 'उच्चतम पात्रता', skills: 'कौशल्ये', previousJobs: 'मागील नोकऱ्या / इंटर्नशिप', roles: 'भूमिका आणि जबाबदाऱ्या', skillsApplied: 'वापरलेली कौशल्ये', certifications: 'प्रमाणपत्रे / उपलब्धी', resume: 'रेझ्युमे / CV', portfolio: 'पोर्टफोलिओ / रेझ्युमे लिंक', workSamples: 'कामाचे नमुने', preferences: 'आवडी आणि मर्यादा', preferencesHelp: 'तुमच्या आयुष्याला अनुरूप संधी सुचवण्यासाठी मदत करा.', yourPreferences: 'तुमच्या प्राधान्यक्रम', requiredNote: '* आवश्यक फील्ड', saveProfile: 'माझे प्रोफाइल जतन करा', saved: 'तुमचे प्रोफाइल स्थानिकरीत्या जतन झाले आहे.' }
en.findJobs.profilePicture = 'Profile picture'
en.findJobs.addProfilePhoto = 'Add profile photo'
en.findJobs.uploadResume = 'Upload resume / CV'
en.findJobs.uploadWorkSamples = 'Upload work samples'
en.findJobs.yourPreferences = 'Your preferences and work constraints'
en.findJobs.preferencesPlaceholder = 'e.g. Cannot work after 7 PM, have childcare responsibilities, unavailable on certain days, prefer nearby jobs, etc.'
hi.findJobs.profilePicture = 'प्रोफ़ाइल फ़ोटो'
hi.findJobs.addProfilePhoto = 'प्रोफ़ाइल फ़ोटो जोड़ें'
hi.findJobs.uploadResume = 'रिज़्यूमे / CV अपलोड करें'
hi.findJobs.uploadWorkSamples = 'कार्य नमूने अपलोड करें'
hi.findJobs.yourPreferences = 'आपकी प्राथमिकताएँ और काम की सीमाएँ'
hi.findJobs.preferencesPlaceholder = 'जैसे, शाम 7 बजे के बाद काम नहीं कर सकती, बच्चों की देखभाल की जिम्मेदारी है, कुछ दिनों में उपलब्ध नहीं हूँ, पास की नौकरी पसंद है, आदि।'
mr.findJobs.profilePicture = 'प्रोफाइल फोटो'
mr.findJobs.addProfilePhoto = 'प्रोफाइल फोटो जोडा'
mr.findJobs.uploadResume = 'रेझ्युमे / CV अपलोड करा'
mr.findJobs.uploadWorkSamples = 'कामाचे नमुने अपलोड करा'
mr.findJobs.yourPreferences = 'तुमच्या आवडी आणि कामाच्या मर्यादा'
mr.findJobs.preferencesPlaceholder = 'उदा. संध्याकाळी 7 नंतर काम करू शकत नाही, बालसंगोपनाची जबाबदारी आहे, काही दिवशी उपलब्ध नाही, जवळच्या नोकऱ्यांना प्राधान्य आहे, इ.'
Object.assign(hi.findJobs, {
  namePlaceholder: 'जैसे, अनन्या शर्मा', emailPlaceholder: 'you@example.com', phonePlaceholder: 'जैसे, 98765 43210', agePlaceholder: 'जैसे, 27', statePlaceholder: 'जैसे, महाराष्ट्र', cityPlaceholder: 'जैसे, पुणे', pincodePlaceholder: '6 अंकों का पिनकोड', qualificationPlaceholder: 'जैसे, बी.कॉम, बैचलर ऑफ कॉमर्स', skillsPlaceholder: 'अपने तकनीकी, पेशेवर और व्यक्तिगत कौशल लिखें।', previousJobsPlaceholder: 'आपने कहाँ काम किया, आपकी पदवी और तारीखें।', rolesPlaceholder: 'हर भूमिका में अपने योगदान का वर्णन करें।', skillsAppliedPlaceholder: 'अपने काम में आपने कौन-से कौशल इस्तेमाल किए?', certificationsPlaceholder: 'पुरस्कार, कोर्स, लाइसेंस या महत्वपूर्ण उपलब्धियाँ।', portfolioPlaceholder: 'पोर्टफोलियो, गूगल ड्राइव या लिंक्डइन लिंक', preferencesPlaceholder: 'जैसे, शाम 7 बजे के बाद काम नहीं कर सकती, बच्चों की देखभाल की ज़िम्मेदारी है, कुछ दिनों में उपलब्ध नहीं हूँ, पास की नौकरी पसंद है, आदि।', resumeHint: 'PDF, DOC या DOCX अपलोड करें', workSamplesHint: 'अपने काम के फ़ोटो, वीडियो या दस्तावेज़'
})
Object.assign(mr.findJobs, {
  namePlaceholder: 'उदा. अनन्या शर्मा', emailPlaceholder: 'you@example.com', phonePlaceholder: 'उदा. 98765 43210', agePlaceholder: 'उदा. 27', statePlaceholder: 'उदा. महाराष्ट्र', cityPlaceholder: 'उदा. पुणे', pincodePlaceholder: '6 अंकी पिनकोड', qualificationPlaceholder: 'उदा. बी.कॉम, वाणिज्य पदवी', skillsPlaceholder: 'तुमची तांत्रिक, व्यावसायिक आणि वैयक्तिक कौशल्ये लिहा.', previousJobsPlaceholder: 'तुम्ही कुठे काम केले, तुमचे पद आणि तारखा.', rolesPlaceholder: 'प्रत्येक भूमिकेतील तुमच्या योगदानाचे वर्णन करा.', skillsAppliedPlaceholder: 'तुम्ही कामात कोणती कौशल्ये वापरली?', certificationsPlaceholder: 'पुरस्कार, अभ्यासक्रम, परवाने किंवा महत्त्वाच्या उपलब्धी.', portfolioPlaceholder: 'पोर्टफोलिओ, गुगल ड्राइव्ह किंवा लिंक्डइन लिंक', preferencesPlaceholder: 'उदा. संध्याकाळी 7 नंतर काम करू शकत नाही, बालसंगोपनाची जबाबदारी आहे, काही दिवशी उपलब्ध नाही, जवळच्या नोकऱ्यांना प्राधान्य आहे, इ.', resumeHint: 'PDF, DOC किंवा DOCX अपलोड करा', workSamplesHint: 'तुमच्या कामाचे फोटो, व्हिडिओ किंवा दस्तऐवज'
})
i18n.use(initReactI18next).init({ resources: { en: { translation: en }, hi: { translation: hi }, mr: { translation: mr } }, lng: localStorage.getItem('wiryaa-language') || 'en', fallbackLng: 'en', interpolation: { escapeValue: false } })
export default i18n
