import { useState } from 'react'
import { FiBriefcase, FiCheckCircle, FiClipboard, FiHome, FiPlus, FiUsers } from 'react-icons/fi'
import '../styles/HireTalentsPage.css'
import logo from '../assets/icons/wiryaa-monogram.png'
import ProfileMenu from '../components/layout/ProfileMenu'

const navItems = [{ id: 'create', label: 'Create Job Post', icon: FiPlus }, { id: 'posts', label: 'View Job Posts', icon: FiClipboard }, { id: 'recommendations', label: 'View Candidate Recommendations', icon: FiUsers }]

function Field({ label, children, required = false }) { return <label className="ht-field"><span>{label}{required && <em> *</em>}</span>{children}</label> }

function CreateJobPost() {
  const [submitted, setSubmitted] = useState(false)
  const handleSubmit = (event) => { event.preventDefault(); if (event.currentTarget.checkValidity()) setSubmitted(true) }
  return <form className="ht-form" onSubmit={handleSubmit}>
    <div className="ht-page-title"><div><p>Employer workspace</p><h1>Create Job Post</h1><span>Share your opportunity and meet talented women ready to make an impact.</span></div><span className="ht-progress"><b>01</b> / 02</span></div>
    <section className="ht-section"><div className="ht-section-heading"><span className="ht-section-number">01</span><div><h2>Company contact information</h2><p>Tell candidates who they will be connecting with.</p></div></div><div className="ht-grid ht-grid-2"><Field label="Name" required><input name="name" required placeholder="e.g. Ananya Sharma" /></Field><Field label="Email"><input name="email" type="email" placeholder="you@company.com" /></Field><Field label="Phone number" required><input name="phone" type="tel" required placeholder="e.g. 98765 43210" /></Field><Field label="Company name" required><input name="companyName" required placeholder="e.g. Acme Technologies" /></Field></div></section>
    <section className="ht-section"><div className="ht-section-heading"><span className="ht-section-number">02</span><div><h2>Job details</h2><p>Give candidates the information they need to decide if this role is right for them.</p></div></div><div className="ht-grid ht-grid-2"><Field label="Job title" required><input name="jobTitle" required placeholder="e.g. Product Designer" /></Field><Field label="Job category" required><select name="category" defaultValue="" required><option value="" disabled>Select a category</option><option>Technology</option><option>Design</option><option>Marketing</option><option>Sales</option><option>Finance</option><option>Operations</option><option>Human Resources</option><option>Customer Support</option><option>Other</option></select></Field><Field label="Job type" required><select name="jobType" defaultValue="" required><option value="" disabled>Select job type</option><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Internship</option><option>Freelance</option><option>Temporary</option></select></Field><Field label="Location" required><input name="location" required placeholder="e.g. Pune, Maharashtra" /></Field></div><Field label="Address"><textarea name="address" placeholder="Office address, landmark or remote-work details" /></Field><Field label="Job description" required><textarea className="ht-large-textarea" name="description" required placeholder="Describe the role, key responsibilities and what a typical day looks like." /></Field><div className="ht-grid ht-grid-2"><Field label="Experience required"><input name="experience" placeholder="e.g. 2–4 years" /></Field><Field label="Salary range"><input name="salary" placeholder="e.g. ₹6,00,000 – ₹9,00,000 per year" /></Field></div><Field label="Benefits"><textarea name="benefits" placeholder="e.g. Flexible hours, health insurance, parental leave, learning budget" /></Field><Field label="Required qualifications" required><textarea name="qualifications" required placeholder="List the education, skills, certifications or qualities needed for this role." /></Field></section>
    <div className="ht-submit-row"><span>* Required fields</span><button className="ht-submit" type="submit">Publish job post <FiCheckCircle /></button></div>{submitted && <div className="ht-success"><FiCheckCircle /> Your job post is ready to publish.</div>}
  </form>
}

function ComingSoon({ page }) { const item = navItems.find((navItem) => navItem.id === page); const Icon = item?.icon || FiBriefcase; return <section className="ht-coming-soon"><span className="ht-coming-icon"><Icon /></span><p>Employer workspace</p><h1>{item?.label}</h1><span>We are thoughtfully shaping this space for you. Check back soon.</span></section> }

function HireTalentsPage() {
  const [page, setPage] = useState('create')
  return <div className="hire-talents-shell"><div className="ht-layout"><div className="ht-profile-corner"><ProfileMenu /></div><aside className="ht-sidebar"><div className="ht-sidebar-top"><a className="ht-brand" href="/"><img src={logo} alt="" /><span>Wiryaa</span></a></div><a className="ht-sidebar-home" href="/"><FiHome /> <span>Back to home</span></a><p>Hiring workspace</p>{navItems.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon /><span>{label}</span>{page === id && <i />}</button>)}<div className="ht-sidebar-tip"><FiUsers /><span>Thoughtful job details help the right candidates find you.</span></div></aside><header className="ht-mobile-header"><a className="ht-brand" href="/"><img src={logo} alt="" /><span>Wiryaa</span></a><span>Employer workspace</span></header><nav className="ht-mobile-nav" aria-label="Hiring workspace">{navItems.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon /><span>{label}</span></button>)}</nav><main className="ht-content">{page === 'create' ? <CreateJobPost /> : <ComingSoon page={page} />}</main></div></div>
}
export default HireTalentsPage
