import { useEffect, useRef, useState } from 'react'
import { FiBriefcase, FiCheckCircle, FiClipboard, FiFileText, FiHome, FiMapPin, FiPlus, FiUsers } from 'react-icons/fi'
import '../styles/HireTalentsPage.css'
import logo from '../assets/icons/wiryaa-monogram.png'
import ProfileMenu from '../components/layout/ProfileMenu'
import api from '../services/api'

const navItems = [{ id: 'create', label: 'Create Job Post', icon: FiPlus }, { id: 'posts', label: 'View Job Posts', icon: FiClipboard }, { id: 'recommendations', label: 'View Candidate Recommendations', icon: FiUsers }]
const categories = ['Technology', 'Design', 'Marketing', 'Sales', 'Finance', 'Operations', 'Human Resources', 'Customer Support', 'Other']
const jobTypes = ['Full-time', 'Part-time', 'Contract', 'Internship', 'Freelance', 'Temporary']

function Field({ label, children, required = false }) { return <label className="ht-field"><span>{label}{required && <em> *</em>}</span>{children}</label> }

function CreateJobPost({ jobPost, loading, onSaved }) {
  const [submitting, setSubmitting] = useState(false); const [submitted, setSubmitted] = useState(false); const [error, setError] = useState(''); const formRef = useRef(null)
  useEffect(() => { if (!submitted) return undefined; const timeout = window.setTimeout(() => setSubmitted(false), 4000); return () => window.clearTimeout(timeout) }, [submitted])
  const markUnsaved = (event) => event.target.closest('.ht-field')?.classList.add('is-dirty')
  const handleSubmit = async (event) => {
    event.preventDefault()
    if (!event.currentTarget.reportValidity()) return
    setSubmitting(true); setSubmitted(false); setError('')
    try { const response = await api.post('/hire-talents/job-post', Object.fromEntries(new FormData(event.currentTarget))); onSaved(response.data.data.jobPost); formRef.current?.querySelectorAll('.is-dirty').forEach((field) => field.classList.remove('is-dirty')); setSubmitted(true) } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save the job post. Please try again.') } finally { setSubmitting(false) }
  }
  if (loading) return <section className="ht-job-status"><i className="ht-spinner" aria-hidden="true" /> Loading job post…</section>
  const isUpdate = Boolean(jobPost)
  return <form ref={formRef} className="ht-form" onSubmit={handleSubmit} onChange={markUnsaved}>
    <div className="ht-page-title"><div><p>Employer workspace</p><h1>{isUpdate ? 'Update Job Post' : 'Create Job Post'}</h1><span>Share your opportunity and meet talented women ready to make an impact.</span></div><span className="ht-progress"><b>01</b> / 02</span></div>
    <section className="ht-section"><div className="ht-section-heading"><span className="ht-section-number">01</span><div><h2>Company contact information</h2><p>Tell candidates who they will be connecting with.</p></div></div><div className="ht-grid ht-grid-2"><Field label="Name" required><input name="name" required defaultValue={jobPost?.name || ''} placeholder="e.g. Ananya Sharma" /></Field><Field label="Email"><input name="email" type="email" defaultValue={jobPost?.email || ''} placeholder="you@company.com" /></Field><Field label="Phone number" required><input name="phone" type="tel" required defaultValue={jobPost?.phone || ''} placeholder="e.g. 98765 43210" /></Field><Field label="Company name" required><input name="companyName" required defaultValue={jobPost?.companyName || ''} placeholder="e.g. Acme Technologies" /></Field></div></section>
    <section className="ht-section"><div className="ht-section-heading"><span className="ht-section-number">02</span><div><h2>Job details</h2><p>Give candidates the information they need to decide if this role is right for them.</p></div></div><div className="ht-grid ht-grid-2"><Field label="Job title" required><input name="jobTitle" required defaultValue={jobPost?.jobTitle || ''} placeholder="e.g. Product Designer" /></Field><Field label="Job category" required><select name="category" defaultValue={jobPost?.category || ''} required><option value="" disabled>Select a category</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Job type" required><select name="jobType" defaultValue={jobPost?.jobType || ''} required><option value="" disabled>Select job type</option>{jobTypes.map((jobType) => <option key={jobType}>{jobType}</option>)}</select></Field><Field label="Location" required><input name="location" required defaultValue={jobPost?.location || ''} placeholder="e.g. Pune, Maharashtra" /></Field></div><Field label="Address"><textarea name="address" defaultValue={jobPost?.address || ''} placeholder="Office address, landmark or remote-work details" /></Field><Field label="Job description" required><textarea className="ht-large-textarea" name="description" required defaultValue={jobPost?.description || ''} placeholder="Describe the role, key responsibilities and what a typical day looks like." /></Field><div className="ht-grid ht-grid-2"><Field label="Experience required"><input name="experience" defaultValue={jobPost?.experience || ''} placeholder="e.g. 2–4 years" /></Field><Field label="Salary range"><input name="salary" defaultValue={jobPost?.salary || ''} placeholder="e.g. ₹6,00,000 – ₹9,00,000 per year" /></Field></div><Field label="Benefits"><textarea name="benefits" defaultValue={jobPost?.benefits || ''} placeholder="e.g. Flexible hours, health insurance, parental leave, learning budget" /></Field><Field label="Required qualifications" required><textarea name="qualifications" required defaultValue={jobPost?.qualifications || ''} placeholder="List the education, skills, certifications or qualities needed for this role." /></Field></section>
    <div className="ht-submit-row"><span>* Required fields</span><button className="ht-submit" type="submit" disabled={submitting} aria-busy={submitting}>{submitting ? <><i className="ht-spinner" aria-hidden="true" /> Saving job post…</> : <>{isUpdate ? 'Save Changes' : 'Publish Job Post'} <FiCheckCircle /></>}</button></div>{submitted && <div className="ht-toast" role="status"><FiCheckCircle /><div><strong>Job post saved</strong><span>Your job post is ready to share.</span></div></div>}{error && <div className="ht-success ht-error" role="alert">{error}</div>}
  </form>
}

function Info({ label, children }) { return <div className="ht-job-info"><span>{label}</span><p>{children || 'Not added'}</p></div> }
function ViewJobPost() {
  const [jobPost, setJobPost] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { let active = true; api.get('/hire-talents/job-post').then((response) => { if (active) setJobPost(response.data.data.jobPost) }).catch((requestError) => { if (active) setError(requestError.response?.data?.message || 'Unable to load the job post.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [])
  if (loading) return <section className="ht-job-status"><i className="ht-spinner" aria-hidden="true" /> Loading job post…</section>
  if (error) return <section className="ht-job-status ht-error" role="alert">{error}</section>
  return <article className="ht-job-page"><div className="ht-page-title"><div><p>Employer workspace</p><h1>Job post</h1><span>A read-only view of your published opportunity.</span></div></div><nav className="ht-job-nav" aria-label="Job post sections"><a href="#contact">Contact</a><a href="#details">Job Details</a><a href="#description">Description</a><a href="#requirements">Requirements</a></nav><header className="ht-job-header"><span className="ht-job-icon"><FiBriefcase /></span><div><p>{jobPost.companyName}</p><h2>{jobPost.jobTitle}</h2><span>{jobPost.jobType} · {jobPost.category}</span></div></header><section className="ht-job-card" id="contact"><h2><FiUsers /> Company / hirer contact information</h2><div className="ht-job-info-grid"><Info label="Name">{jobPost.name}</Info><Info label="Company name">{jobPost.companyName}</Info><Info label="Email">{jobPost.email || 'Not added'}</Info><Info label="Phone number">{jobPost.phone}</Info></div></section><section className="ht-job-card" id="details"><h2><FiMapPin /> Job details</h2><div className="ht-job-info-grid"><Info label="Job category">{jobPost.category}</Info><Info label="Job type">{jobPost.jobType}</Info><Info label="Location">{jobPost.location}</Info><Info label="Address">{jobPost.address}</Info><Info label="Experience required">{jobPost.experience}</Info><Info label="Salary range">{jobPost.salary}</Info></div></section><section className="ht-job-card" id="description"><h2><FiFileText /> Job description</h2><p>{jobPost.description}</p></section><section className="ht-job-card" id="requirements"><h2>Benefits & qualifications</h2><div className="ht-job-info-grid"><Info label="Benefits">{jobPost.benefits}</Info><Info label="Required qualifications">{jobPost.qualifications}</Info></div></section></article>
}

function ComingSoon({ page }) { const item = navItems.find((navItem) => navItem.id === page); const Icon = item?.icon || FiBriefcase; return <section className="ht-coming-soon"><span className="ht-coming-icon"><Icon /></span><p>Employer workspace</p><h1>{item?.label}</h1><span>We are thoughtfully shaping this space for you. Check back soon.</span></section> }

function HireTalentsPage() {
  const [page, setPage] = useState('create'); const [jobPost, setJobPost] = useState(null); const [loadingJobPost, setLoadingJobPost] = useState(true)
  useEffect(() => { let active = true; api.get('/hire-talents/job-post').then((response) => { if (active) setJobPost(response.data.data.jobPost) }).catch((requestError) => { if (requestError.response?.status !== 404 && active) setJobPost(null) }).finally(() => { if (active) setLoadingJobPost(false) }); return () => { active = false } }, [])
  const createLabel = jobPost ? 'Update Job Post' : 'Create Job Post'
  return <div className="hire-talents-shell"><div className="ht-layout"><div className="ht-profile-corner"><ProfileMenu /></div><aside className="ht-sidebar"><div className="ht-sidebar-top"><a className="ht-brand" href="/"><img src={logo} alt="" /><span>Wiryaa</span></a></div><a className="ht-sidebar-home" href="/"><FiHome /> <span>Back to home</span></a><p>Hiring workspace</p>{navItems.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon /><span>{id === 'create' ? createLabel : label}</span>{page === id && <i />}</button>)}<div className="ht-sidebar-tip"><FiUsers /><span>Thoughtful job details help the right candidates find you.</span></div></aside><header className="ht-mobile-header"><a className="ht-brand" href="/"><img src={logo} alt="" /><span>Wiryaa</span></a><span>Employer workspace</span></header><nav className="ht-mobile-nav" aria-label="Hiring workspace">{navItems.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon /><span>{id === 'create' ? createLabel : label}</span></button>)}</nav><main className="ht-content">{page === 'create' ? <CreateJobPost key={jobPost?._id || 'new'} jobPost={jobPost} loading={loadingJobPost} onSaved={setJobPost} /> : page === 'posts' ? <ViewJobPost /> : <ComingSoon page={page} />}</main></div></div>
}
export default HireTalentsPage
