import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { FiEye, FiEyeOff } from 'react-icons/fi'
import AuthShell from '../components/auth/AuthShell'
import api from '../services/api'
import { saveSession } from '../services/authStorage'
import { useTranslation } from 'react-i18next'

const initialValues = { fullName: '', email: '', mobile: '', password: '', confirmPassword: '', gender: '' }
function SignupPage() {
  const { t } = useTranslation()
  const [values, setValues] = useState(initialValues); const [errors, setErrors] = useState({}); const [formError, setFormError] = useState(''); const [loading, setLoading] = useState(false); const location = useLocation(); const navigate = useNavigate()
  const validate = () => { const next = {}; if (!values.fullName.trim()) next.fullName = t('auth.validation.fullName'); if (!values.email.trim() && !values.mobile.trim()) next.contact = t('auth.validation.contact'); if (values.email && !/^\S+@\S+\.\S+$/.test(values.email)) next.email = t('auth.validation.validEmail'); if (values.mobile && !/^[0-9+\-()\s]{7,18}$/.test(values.mobile)) next.mobile = t('auth.validation.validMobile'); if (!values.password) next.password = t('auth.validation.createPassword'); else if (values.password.length < 8) next.password = t('auth.validation.passwordLength'); if (!values.confirmPassword) next.confirmPassword = t('auth.validation.confirmPassword'); else if (values.password !== values.confirmPassword) next.confirmPassword = t('auth.validation.passwordMismatch'); if (!values.gender) next.gender = t('auth.validation.gender'); return next }
  const change = ({ target }) => { setValues((current) => ({ ...current, [target.name]: target.value })); setFormError('') }
  const submit = async (event) => { event.preventDefault(); const next = validate(); setErrors(next); if (Object.keys(next).length) return; setLoading(true); try { const { data } = await api.post('/auth/signup', values); saveSession(data.data); navigate('/language', { replace: true, state: { destination: location.state?.destination || '/' } }) } catch (error) { setFormError(error.response?.data?.message || t('auth.validation.signupFailed')) } finally { setLoading(false) } }
  return <AuthShell mode="signup"><div className="auth-card-heading"><p>{t('auth.createYourAccount')}</p><h2 id="auth-title">{t('auth.join')}</h2><span>{t('auth.existingUser')} <Link to="/login" state={location.state}>{t('auth.login')}</Link></span></div>{formError && <div className="form-api-error" role="alert">{formError}</div>}<form className="auth-form" noValidate onSubmit={submit}><Field label={t('auth.fullName')} name="fullName" value={values.fullName} error={errors.fullName} onChange={change} autoComplete="name" /><div className="auth-contact-label">{t('auth.contactDetails')} <span>{t('auth.either')}</span></div>{errors.contact && <p className="form-error contact-error">{errors.contact}</p>}<div className="auth-form-grid"><Field label={t('auth.email')} name="email" type="email" value={values.email} error={errors.email} onChange={change} autoComplete="email" /><Field label={t('auth.mobile')} name="mobile" type="tel" value={values.mobile} error={errors.mobile} onChange={change} autoComplete="tel" /></div><div className="auth-form-grid"><Field label={t('auth.password')} name="password" type="password" value={values.password} error={errors.password} onChange={change} autoComplete="new-password" /><Field label={t('auth.confirmPassword')} name="confirmPassword" type="password" value={values.confirmPassword} error={errors.confirmPassword} onChange={change} autoComplete="new-password" /></div><fieldset className={`gender-field ${errors.gender ? 'has-error' : ''}`}><legend>{t('auth.gender')}</legend><div className="gender-options"><label><input type="radio" name="gender" value="Female" checked={values.gender === 'Female'} onChange={change} /> <span>{t('auth.female')}</span></label><label><input type="radio" name="gender" value="Male" checked={values.gender === 'Male'} onChange={change} /> <span>{t('auth.male')}</span></label></div>{errors.gender && <p className="form-error">{errors.gender}</p>}</fieldset><button className="auth-submit" type="submit" disabled={loading}>{t(loading ? 'auth.creating' : 'auth.create')}</button></form></AuthShell>
}
function Field({ label, name, type = 'text', value, error, onChange, autoComplete }) { const { t } = useTranslation(); const [visible, setVisible] = useState(false); const isPassword = type === 'password'; return <label className={`form-field ${error ? 'has-error' : ''}`}><span>{label}</span><span className="password-input-wrap"><input name={name} type={isPassword && visible ? 'text' : type} value={value} onChange={onChange} autoComplete={autoComplete} aria-invalid={Boolean(error)} />{isPassword && <button className="password-toggle" type="button" onClick={() => setVisible((current) => !current)} aria-label={`${t(visible ? 'auth.hide' : 'auth.show')} ${label.toLowerCase()}`}>{visible ? <FiEyeOff /> : <FiEye />}</button>}</span>{error && <small className="form-error">{error}</small>}</label> }
export default SignupPage
