import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { FiEye, FiEyeOff } from 'react-icons/fi'
import AuthShell from '../components/auth/AuthShell'
import api from '../services/api'
import { saveSession } from '../services/authStorage'

const initialValues = { fullName: '', email: '', mobile: '', password: '', confirmPassword: '', gender: '' }
function SignupPage() {
  const [values, setValues] = useState(initialValues); const [errors, setErrors] = useState({}); const [formError, setFormError] = useState(''); const [loading, setLoading] = useState(false); const location = useLocation(); const navigate = useNavigate()
  const validate = () => { const next = {}; if (!values.fullName.trim()) next.fullName = 'Please enter your full name.'; if (!values.email.trim() && !values.mobile.trim()) next.contact = 'Enter an email address or mobile number.'; if (values.email && !/^\S+@\S+\.\S+$/.test(values.email)) next.email = 'Enter a valid email address.'; if (values.mobile && !/^[0-9+\-()\s]{7,18}$/.test(values.mobile)) next.mobile = 'Enter a valid mobile number.'; if (!values.password) next.password = 'Please create a password.'; else if (values.password.length < 8) next.password = 'Password must be at least 8 characters.'; if (!values.confirmPassword) next.confirmPassword = 'Please confirm your password.'; else if (values.password !== values.confirmPassword) next.confirmPassword = 'Passwords do not match.'; if (!values.gender) next.gender = 'Please select your gender.'; return next }
  const change = ({ target }) => { setValues((current) => ({ ...current, [target.name]: target.value })); setFormError('') }
  const submit = async (event) => { event.preventDefault(); const next = validate(); setErrors(next); if (Object.keys(next).length) return; setLoading(true); try { const { data } = await api.post('/auth/signup', values); saveSession(data.data); navigate('/language', { replace: true, state: { destination: location.state?.destination || '/' } }) } catch (error) { setFormError(error.response?.data?.message || 'Unable to create your account. Please try again.') } finally { setLoading(false) } }
  return <AuthShell mode="signup"><div className="auth-card-heading"><p>CREATE YOUR ACCOUNT</p><h2 id="auth-title">Join Wiryaa</h2><span>Already have an account? <Link to="/login" state={location.state}>Log in</Link></span></div>{formError && <div className="form-api-error" role="alert">{formError}</div>}<form className="auth-form" noValidate onSubmit={submit}><Field label="Full name" name="fullName" value={values.fullName} error={errors.fullName} onChange={change} autoComplete="name" /><div className="auth-contact-label">Contact details <span>Use either one</span></div>{errors.contact && <p className="form-error contact-error">{errors.contact}</p>}<div className="auth-form-grid"><Field label="Email address" name="email" type="email" value={values.email} error={errors.email} onChange={change} autoComplete="email" /><Field label="Mobile number" name="mobile" type="tel" value={values.mobile} error={errors.mobile} onChange={change} autoComplete="tel" /></div><div className="auth-form-grid"><Field label="Password" name="password" type="password" value={values.password} error={errors.password} onChange={change} autoComplete="new-password" /><Field label="Confirm password" name="confirmPassword" type="password" value={values.confirmPassword} error={errors.confirmPassword} onChange={change} autoComplete="new-password" /></div><fieldset className={`gender-field ${errors.gender ? 'has-error' : ''}`}><legend>Gender</legend><div className="gender-options"><label><input type="radio" name="gender" value="Female" checked={values.gender === 'Female'} onChange={change} /> <span>Female</span></label><label><input type="radio" name="gender" value="Male" checked={values.gender === 'Male'} onChange={change} /> <span>Male</span></label></div>{errors.gender && <p className="form-error">{errors.gender}</p>}</fieldset><button className="auth-submit" type="submit" disabled={loading}>{loading ? 'Creating account…' : 'Create account'}</button></form></AuthShell>
}
function Field({ label, name, type = 'text', value, error, onChange, autoComplete }) { const [visible, setVisible] = useState(false); const isPassword = type === 'password'; return <label className={`form-field ${error ? 'has-error' : ''}`}><span>{label}</span><span className="password-input-wrap"><input name={name} type={isPassword && visible ? 'text' : type} value={value} onChange={onChange} autoComplete={autoComplete} aria-invalid={Boolean(error)} />{isPassword && <button className="password-toggle" type="button" onClick={() => setVisible((current) => !current)} aria-label={`${visible ? 'Hide' : 'Show'} ${label.toLowerCase()}`}>{visible ? <FiEyeOff /> : <FiEye />}</button>}</span>{error && <small className="form-error">{error}</small>}</label> }
export default SignupPage
