require('dotenv').config()
const express = require('express')
const cors = require('cors')
const connectDatabase = require('./config/db')
const corsOptions = require('./config/cors')
const authRoutes = require('./routes/authRoutes')
const userRoutes = require('./routes/userRoutes')
const jobRoutes = require('./routes/jobRoutes')
const hireTalentsRoutes = require('./routes/hireTalentsRoutes')
const { notFound, errorHandler } = require('./middleware/errorHandler')

const app = express()
app.use(cors(corsOptions))
app.use(express.json({ limit: '10kb' }))
app.get('/api/health', (req, res) => res.status(200).json({ status: 'success' }))
app.use('/api/auth', authRoutes)
app.use('/api/users', userRoutes)
app.use('/api/jobs', jobRoutes)
app.use('/api/hire-talents', hireTalentsRoutes)
app.use(notFound)
app.use(errorHandler)

const port = process.env.PORT || 5000
connectDatabase()
  .then(() => app.listen(port, () => console.log(`API listening on port ${port}`)))
  .catch((error) => { console.error('Database connection failed:', error.message); process.exit(1) })
